version: '3.9'

services:
  addoperatorservice:
    image: ${DOCKER_REGISTRY-}addoperatorservice
    build:
      context: .
      dockerfile: AddOperatorService/Dockerfile
    depends_on:
      - addOperations-db
      - zipkin 
    # ports:
    #   - 2222:80
    deploy:
      mode: replicated
      replicas: 3

  calculatorwebui:
    image: ${DOCKER_REGISTRY-}calculatorwebui
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    depends_on:
      - addoperatorservice
      - subtractoperatorservice
      - zipkin

  subtractoperatorservice:
    image: ${DOCKER_REGISTRY-}subtractoperatorservice
    build:
      context: .
      dockerfile: SubtractOperatorService/Dockerfile
    depends_on:
      - subtractOperations-db
    deploy:
      mode: replicated
      replicas: 3

  addOperations-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "addOperations-database"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  subtractOperations-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "subtractOperations-database"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    # environment:
    #   - STORAGE_TYPE=mysql
    #   - MYSQL_HOST=zipkin-storage
    #   - MYSQL_USER=zipkin
    #   - MYSQL_PASS=zipkin
    # depends_on:
    #   - zipkin-storage

  # zipkin-storage:
  #   image: openzipkin/zipkin-mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - zipkin_data:/mysql/data

volumes:
  rps_seq_data:
  zipkin_data:

