version: '3.9'

services:
  addoperatorservice:
    image: ${DOCKER_REGISTRY-}addoperatorservice
    build:
      context: .
      dockerfile: AddOperatorService/Dockerfile
    deploy:
      mode: replicated
      replicas: 3

  calculatorwebui:
    image: ${DOCKER_REGISTRY-}calculatorwebui
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    depends_on:
      - addoperatorservice
      - subtractoperatorservice

  subtractoperatorservice:
    image: ${DOCKER_REGISTRY-}subtractoperatorservice
    build:
      context: .
      dockerfile: SubtractOperatorService/Dockerfile
    deploy:
      mode: replicated
      replicas: 3

