version: '3.9'

services:
  addoperatorservice:
    image: ${DOCKER_REGISTRY-}addoperatorservice
    build:
      context: .
      dockerfile: AddOperatorService/Dockerfile
    depends_on:
      - addOperations-db
    deploy:
      mode: replicated
      replicas: 3

  calculatorwebui:
    image: ${DOCKER_REGISTRY-}calculatorwebui
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    depends_on:
      - addoperatorservice
      - subtractoperatorservice

  subtractoperatorservice:
    image: ${DOCKER_REGISTRY-}subtractoperatorservice
    build:
      context: .
      dockerfile: SubtractOperatorService/Dockerfile
    depends_on:
      - subtractOperations-db
    deploy:
      mode: replicated
      replicas: 3

  addOperations-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "addOperations-database"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  subtractOperations-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "subtractOperations-database"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

